package com.example.jeampierre.titanicshop.daogenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.jeampierre.titanicshop.daogenerator.Producto;
import com.example.jeampierre.titanicshop.daogenerator.Categoria;
import com.example.jeampierre.titanicshop.daogenerator.Orden;
import com.example.jeampierre.titanicshop.daogenerator.Factura;
import com.example.jeampierre.titanicshop.daogenerator.Cliente;

import com.example.jeampierre.titanicshop.daogenerator.ProductoDao;
import com.example.jeampierre.titanicshop.daogenerator.CategoriaDao;
import com.example.jeampierre.titanicshop.daogenerator.OrdenDao;
import com.example.jeampierre.titanicshop.daogenerator.FacturaDao;
import com.example.jeampierre.titanicshop.daogenerator.ClienteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productoDaoConfig;
    private final DaoConfig categoriaDaoConfig;
    private final DaoConfig ordenDaoConfig;
    private final DaoConfig facturaDaoConfig;
    private final DaoConfig clienteDaoConfig;

    private final ProductoDao productoDao;
    private final CategoriaDao categoriaDao;
    private final OrdenDao ordenDao;
    private final FacturaDao facturaDao;
    private final ClienteDao clienteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productoDaoConfig = daoConfigMap.get(ProductoDao.class).clone();
        productoDaoConfig.initIdentityScope(type);

        categoriaDaoConfig = daoConfigMap.get(CategoriaDao.class).clone();
        categoriaDaoConfig.initIdentityScope(type);

        ordenDaoConfig = daoConfigMap.get(OrdenDao.class).clone();
        ordenDaoConfig.initIdentityScope(type);

        facturaDaoConfig = daoConfigMap.get(FacturaDao.class).clone();
        facturaDaoConfig.initIdentityScope(type);

        clienteDaoConfig = daoConfigMap.get(ClienteDao.class).clone();
        clienteDaoConfig.initIdentityScope(type);

        productoDao = new ProductoDao(productoDaoConfig, this);
        categoriaDao = new CategoriaDao(categoriaDaoConfig, this);
        ordenDao = new OrdenDao(ordenDaoConfig, this);
        facturaDao = new FacturaDao(facturaDaoConfig, this);
        clienteDao = new ClienteDao(clienteDaoConfig, this);

        registerDao(Producto.class, productoDao);
        registerDao(Categoria.class, categoriaDao);
        registerDao(Orden.class, ordenDao);
        registerDao(Factura.class, facturaDao);
        registerDao(Cliente.class, clienteDao);
    }
    
    public void clear() {
        productoDaoConfig.getIdentityScope().clear();
        categoriaDaoConfig.getIdentityScope().clear();
        ordenDaoConfig.getIdentityScope().clear();
        facturaDaoConfig.getIdentityScope().clear();
        clienteDaoConfig.getIdentityScope().clear();
    }

    public ProductoDao getProductoDao() {
        return productoDao;
    }

    public CategoriaDao getCategoriaDao() {
        return categoriaDao;
    }

    public OrdenDao getOrdenDao() {
        return ordenDao;
    }

    public FacturaDao getFacturaDao() {
        return facturaDao;
    }

    public ClienteDao getClienteDao() {
        return clienteDao;
    }

}
